apiVersion: v1
kind: Service
metadata:
  name: ingress-expose-http
  namespace: ingress-nginx 
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 172.16.13.207

---

apiVersion: v1
kind: Service
metadata:
  name: ingress-expose-https
  namespace: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  externalIPs:
    - 172.16.13.207

